package model;

// Generated 2015/1/6 �U�� 07:36:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * BoardGames generated by hbm2java
 */
public class BoardGames implements java.io.Serializable {

	private int boardGamesId;
	private StoreMember storeMember;
	private BoardGameKind boardGameKind;
	private String storeName;
	private String boardGameEnglishName;
	private String boardGameName;
	private String boardGameNumber;
	private String imgFileName;
	private byte[] boardGameImage;
	private String boardGameExplan;
	private Set<BoardGames_Image> boardGamesImages = new HashSet<BoardGames_Image>(
			0);

	public BoardGames() {
	}

	public BoardGames(int boardGamesId) {
		this.boardGamesId = boardGamesId;
	}

	public BoardGames(int boardGamesId, StoreMember storeMember,
			BoardGameKind boardGameKind, String storeName,
			String boardGameEnglishName, String boardGameName,
			String boardGameNumber, String imgFileName, byte[] boardGameImage,
			String boardGameExplan, Set<BoardGames_Image> boardGamesImages) {
		this.boardGamesId = boardGamesId;
		this.storeMember = storeMember;
		this.boardGameKind = boardGameKind;
		this.storeName = storeName;
		this.boardGameEnglishName = boardGameEnglishName;
		this.boardGameName = boardGameName;
		this.boardGameNumber = boardGameNumber;
		this.imgFileName = imgFileName;
		this.boardGameImage = boardGameImage;
		this.boardGameExplan = boardGameExplan;
		this.boardGamesImages = boardGamesImages;
	}

	public int getBoardGamesId() {
		return this.boardGamesId;
	}

	public void setBoardGamesId(int boardGamesId) {
		this.boardGamesId = boardGamesId;
	}

	public StoreMember getStoreMember() {
		return this.storeMember;
	}

	public void setStoreMember(StoreMember storeMember) {
		this.storeMember = storeMember;
	}

	public BoardGameKind getBoardGameKind() {
		return this.boardGameKind;
	}

	public void setBoardGameKind(BoardGameKind boardGameKind) {
		this.boardGameKind = boardGameKind;
	}

	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	public String getBoardGameEnglishName() {
		return this.boardGameEnglishName;
	}

	public void setBoardGameEnglishName(String boardGameEnglishName) {
		this.boardGameEnglishName = boardGameEnglishName;
	}

	public String getBoardGameName() {
		return this.boardGameName;
	}

	public void setBoardGameName(String boardGameName) {
		this.boardGameName = boardGameName;
	}

	public String getBoardGameNumber() {
		return this.boardGameNumber;
	}

	public void setBoardGameNumber(String boardGameNumber) {
		this.boardGameNumber = boardGameNumber;
	}

	public String getImgFileName() {
		return this.imgFileName;
	}

	public void setImgFileName(String imgFileName) {
		this.imgFileName = imgFileName;
	}

	public byte[] getBoardGameImage() {
		return this.boardGameImage;
	}

	public void setBoardGameImage(byte[] boardGameImage) {
		this.boardGameImage = boardGameImage;
	}

	public String getBoardGameExplan() {
		return this.boardGameExplan;
	}

	public void setBoardGameExplan(String boardGameExplan) {
		this.boardGameExplan = boardGameExplan;
	}

	public Set<BoardGames_Image> getBoardGamesImages() {
		return this.boardGamesImages;
	}

	public void setBoardGamesImages(Set<BoardGames_Image> boardGamesImages) {
		this.boardGamesImages = boardGamesImages;
	}

}
