package model;

// Generated 2015/1/6 �U�� 07:36:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * BoardGameKind generated by hbm2java
 */
public class BoardGameKind implements java.io.Serializable {

	private int boardGameSerialNumber;
	private String boardGameStyle;
	private Set<GroupChoiceGames> groupChoiceGameses = new HashSet<GroupChoiceGames>(
			0);
	private Set<BoardGames> boardGameses = new HashSet<BoardGames>(0);

	public BoardGameKind() {
	}

	public BoardGameKind(int boardGameSerialNumber) {
		this.boardGameSerialNumber = boardGameSerialNumber;
	}

	public BoardGameKind(int boardGameSerialNumber, String boardGameStyle,
			Set<GroupChoiceGames> groupChoiceGameses,
			Set<BoardGames> boardGameses) {
		this.boardGameSerialNumber = boardGameSerialNumber;
		this.boardGameStyle = boardGameStyle;
		this.groupChoiceGameses = groupChoiceGameses;
		this.boardGameses = boardGameses;
	}

	public int getBoardGameSerialNumber() {
		return this.boardGameSerialNumber;
	}

	public void setBoardGameSerialNumber(int boardGameSerialNumber) {
		this.boardGameSerialNumber = boardGameSerialNumber;
	}

	public String getBoardGameStyle() {
		return this.boardGameStyle;
	}

	public void setBoardGameStyle(String boardGameStyle) {
		this.boardGameStyle = boardGameStyle;
	}

	public Set<GroupChoiceGames> getGroupChoiceGameses() {
		return this.groupChoiceGameses;
	}

	public void setGroupChoiceGameses(Set<GroupChoiceGames> groupChoiceGameses) {
		this.groupChoiceGameses = groupChoiceGameses;
	}

	public Set<BoardGames> getBoardGameses() {
		return this.boardGameses;
	}

	public void setBoardGameses(Set<BoardGames> boardGameses) {
		this.boardGameses = boardGameses;
	}

}
