package model;

// Generated 2015/1/6 �W�� 11:59:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GroupRoom generated by hbm2java
 */
public class GroupRoom implements java.io.Serializable {

	private int groupSerialNumber;
	private StoreMember storeMember;
	private Member member;
	private String storeName;
	private Date groupStartTime;
	private Date groupEndTime;
	private String groupRoomName;
	private String groupSuggestNumber;
	private Integer groupLowerLimit;
	private Integer groupUpperLimit;
	private Date groupGameTime;
	private Date reserveGroupStartTime;
	private Date reserveGroupEndTime;
	private Integer roomState;
	private String imgFileName;
	private byte[] privateGroupImage;
	private Set<GroupRoom_Info> groupRoomInfos = new HashSet<GroupRoom_Info>(0);
	private Set<Joiner_Info> joinerInfos = new HashSet<Joiner_Info>(0);
	private Set<GroupRoom_Message> groupRoomMessages = new HashSet<GroupRoom_Message>(
			0);
	private Set<GroupChoiceGames> groupChoiceGameses = new HashSet<GroupChoiceGames>(
			0);

	public GroupRoom() {
	}

	public GroupRoom(int groupSerialNumber) {
		this.groupSerialNumber = groupSerialNumber;
	}

	public GroupRoom(int groupSerialNumber, StoreMember storeMember,
			Member member, String storeName, Date groupStartTime,
			Date groupEndTime, String groupRoomName,
			String groupSuggestNumber, Integer groupLowerLimit,
			Integer groupUpperLimit, Date groupGameTime,
			Date reserveGroupStartTime, Date reserveGroupEndTime,
			Integer roomState, String imgFileName, byte[] privateGroupImage,
			Set<GroupRoom_Info> groupRoomInfos, Set<Joiner_Info> joinerInfos,
			Set<GroupRoom_Message> groupRoomMessages,
			Set<GroupChoiceGames> groupChoiceGameses) {
		this.groupSerialNumber = groupSerialNumber;
		this.storeMember = storeMember;
		this.member = member;
		this.storeName = storeName;
		this.groupStartTime = groupStartTime;
		this.groupEndTime = groupEndTime;
		this.groupRoomName = groupRoomName;
		this.groupSuggestNumber = groupSuggestNumber;
		this.groupLowerLimit = groupLowerLimit;
		this.groupUpperLimit = groupUpperLimit;
		this.groupGameTime = groupGameTime;
		this.reserveGroupStartTime = reserveGroupStartTime;
		this.reserveGroupEndTime = reserveGroupEndTime;
		this.roomState = roomState;
		this.imgFileName = imgFileName;
		this.privateGroupImage = privateGroupImage;
		this.groupRoomInfos = groupRoomInfos;
		this.joinerInfos = joinerInfos;
		this.groupRoomMessages = groupRoomMessages;
		this.groupChoiceGameses = groupChoiceGameses;
	}

	public int getGroupSerialNumber() {
		return this.groupSerialNumber;
	}

	public void setGroupSerialNumber(int groupSerialNumber) {
		this.groupSerialNumber = groupSerialNumber;
	}

	public StoreMember getStoreMember() {
		return this.storeMember;
	}

	public void setStoreMember(StoreMember storeMember) {
		this.storeMember = storeMember;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	public Date getGroupStartTime() {
		return this.groupStartTime;
	}

	public void setGroupStartTime(Date groupStartTime) {
		this.groupStartTime = groupStartTime;
	}

	public Date getGroupEndTime() {
		return this.groupEndTime;
	}

	public void setGroupEndTime(Date groupEndTime) {
		this.groupEndTime = groupEndTime;
	}

	public String getGroupRoomName() {
		return this.groupRoomName;
	}

	public void setGroupRoomName(String groupRoomName) {
		this.groupRoomName = groupRoomName;
	}

	public String getGroupSuggestNumber() {
		return this.groupSuggestNumber;
	}

	public void setGroupSuggestNumber(String groupSuggestNumber) {
		this.groupSuggestNumber = groupSuggestNumber;
	}

	public Integer getGroupLowerLimit() {
		return this.groupLowerLimit;
	}

	public void setGroupLowerLimit(Integer groupLowerLimit) {
		this.groupLowerLimit = groupLowerLimit;
	}

	public Integer getGroupUpperLimit() {
		return this.groupUpperLimit;
	}

	public void setGroupUpperLimit(Integer groupUpperLimit) {
		this.groupUpperLimit = groupUpperLimit;
	}

	public Date getGroupGameTime() {
		return this.groupGameTime;
	}

	public void setGroupGameTime(Date groupGameTime) {
		this.groupGameTime = groupGameTime;
	}

	public Date getReserveGroupStartTime() {
		return this.reserveGroupStartTime;
	}

	public void setReserveGroupStartTime(Date reserveGroupStartTime) {
		this.reserveGroupStartTime = reserveGroupStartTime;
	}

	public Date getReserveGroupEndTime() {
		return this.reserveGroupEndTime;
	}

	public void setReserveGroupEndTime(Date reserveGroupEndTime) {
		this.reserveGroupEndTime = reserveGroupEndTime;
	}

	public Integer getRoomState() {
		return this.roomState;
	}

	public void setRoomState(Integer roomState) {
		this.roomState = roomState;
	}

	public String getImgFileName() {
		return this.imgFileName;
	}

	public void setImgFileName(String imgFileName) {
		this.imgFileName = imgFileName;
	}

	public byte[] getPrivateGroupImage() {
		return this.privateGroupImage;
	}

	public void setPrivateGroupImage(byte[] privateGroupImage) {
		this.privateGroupImage = privateGroupImage;
	}

	public Set<GroupRoom_Info> getGroupRoomInfos() {
		return this.groupRoomInfos;
	}

	public void setGroupRoomInfos(Set<GroupRoom_Info> groupRoomInfos) {
		this.groupRoomInfos = groupRoomInfos;
	}

	public Set<Joiner_Info> getJoinerInfos() {
		return this.joinerInfos;
	}

	public void setJoinerInfos(Set<Joiner_Info> joinerInfos) {
		this.joinerInfos = joinerInfos;
	}

	public Set<GroupRoom_Message> getGroupRoomMessages() {
		return this.groupRoomMessages;
	}

	public void setGroupRoomMessages(Set<GroupRoom_Message> groupRoomMessages) {
		this.groupRoomMessages = groupRoomMessages;
	}

	public Set<GroupChoiceGames> getGroupChoiceGameses() {
		return this.groupChoiceGameses;
	}

	public void setGroupChoiceGameses(Set<GroupChoiceGames> groupChoiceGameses) {
		this.groupChoiceGameses = groupChoiceGameses;
	}

}
