package model;

// Generated 2015/1/6 �W�� 11:59:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GroupRoomMessage generated by hbm2java
 */
public class GroupRoom_Message implements java.io.Serializable {

	private int groupRoomMessageSerialNumber;
	private GroupRoom groupRoom;
	private String messageUsername;
	private String messageContents;
	private Date messageTime;

	public GroupRoom_Message() {
	}

	public GroupRoom_Message(int groupRoomMessageSerialNumber) {
		this.groupRoomMessageSerialNumber = groupRoomMessageSerialNumber;
	}

	public GroupRoom_Message(int groupRoomMessageSerialNumber,
			GroupRoom groupRoom, String messageUsername,
			String messageContents, Date messageTime) {
		this.groupRoomMessageSerialNumber = groupRoomMessageSerialNumber;
		this.groupRoom = groupRoom;
		this.messageUsername = messageUsername;
		this.messageContents = messageContents;
		this.messageTime = messageTime;
	}

	public int getGroupRoomMessageSerialNumber() {
		return this.groupRoomMessageSerialNumber;
	}

	public void setGroupRoomMessageSerialNumber(int groupRoomMessageSerialNumber) {
		this.groupRoomMessageSerialNumber = groupRoomMessageSerialNumber;
	}

	public GroupRoom getGroupRoom() {
		return this.groupRoom;
	}

	public void setGroupRoom(GroupRoom groupRoom) {
		this.groupRoom = groupRoom;
	}

	public String getMessageUsername() {
		return this.messageUsername;
	}

	public void setMessageUsername(String messageUsername) {
		this.messageUsername = messageUsername;
	}

	public String getMessageContents() {
		return this.messageContents;
	}

	public void setMessageContents(String messageContents) {
		this.messageContents = messageContents;
	}

	public Date getMessageTime() {
		return this.messageTime;
	}

	public void setMessageTime(Date messageTime) {
		this.messageTime = messageTime;
	}

}
