package model;

// Generated 2015/1/6 �W�� 11:59:56 by Hibernate Tools 3.4.0.CR1

/**
 * GroupRoomInfo generated by hbm2java
 */
public class GroupRoom_Info implements java.io.Serializable {

	private int groupPictureSerialNumber;
	private GroupRoom groupRoom;
	private byte[] groupPicture;
	private String imgFileName;

	public GroupRoom_Info() {
	}

	public GroupRoom_Info(int groupPictureSerialNumber) {
		this.groupPictureSerialNumber = groupPictureSerialNumber;
	}

	public GroupRoom_Info(int groupPictureSerialNumber, GroupRoom groupRoom,
			byte[] groupPicture, String imgFileName) {
		this.groupPictureSerialNumber = groupPictureSerialNumber;
		this.groupRoom = groupRoom;
		this.groupPicture = groupPicture;
		this.imgFileName = imgFileName;
	}

	public int getGroupPictureSerialNumber() {
		return this.groupPictureSerialNumber;
	}

	public void setGroupPictureSerialNumber(int groupPictureSerialNumber) {
		this.groupPictureSerialNumber = groupPictureSerialNumber;
	}

	public GroupRoom getGroupRoom() {
		return this.groupRoom;
	}

	public void setGroupRoom(GroupRoom groupRoom) {
		this.groupRoom = groupRoom;
	}

	public byte[] getGroupPicture() {
		return this.groupPicture;
	}

	public void setGroupPicture(byte[] groupPicture) {
		this.groupPicture = groupPicture;
	}

	public String getImgFileName() {
		return this.imgFileName;
	}

	public void setImgFileName(String imgFileName) {
		this.imgFileName = imgFileName;
	}

}
