package model;

// Generated 2015/1/6 �W�� 11:59:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * JoinerInfo generated by hbm2java
 */
public class Joiner_Info implements java.io.Serializable {

	private int joinerInfoSerialNumber;
	private GroupRoom groupRoom;
	private Date joinTime;
	private String username;

	public Joiner_Info() {
	}

	public Joiner_Info(int joinerInfoSerialNumber) {
		this.joinerInfoSerialNumber = joinerInfoSerialNumber;
	}

	public Joiner_Info(int joinerInfoSerialNumber, GroupRoom groupRoom,
			Date joinTime, String username) {
		this.joinerInfoSerialNumber = joinerInfoSerialNumber;
		this.groupRoom = groupRoom;
		this.joinTime = joinTime;
		this.username = username;
	}

	public int getJoinerInfoSerialNumber() {
		return this.joinerInfoSerialNumber;
	}

	public void setJoinerInfoSerialNumber(int joinerInfoSerialNumber) {
		this.joinerInfoSerialNumber = joinerInfoSerialNumber;
	}

	public GroupRoom getGroupRoom() {
		return this.groupRoom;
	}

	public void setGroupRoom(GroupRoom groupRoom) {
		this.groupRoom = groupRoom;
	}

	public Date getJoinTime() {
		return this.joinTime;
	}

	public void setJoinTime(Date joinTime) {
		this.joinTime = joinTime;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
