package model;

// Generated 2015/1/6 �W�� 11:59:56 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	private int memberId;
	private String username;
	private byte[] pswd;
	private String email;
	private String lastname;
	private String firstname;
	private String gender;
	private Serializable nickname;
	private Date birthday;
	private String idCard;
	private Date joinDate;
	private String phone;
	private String memberAddress;
	private String imgFileName;
	private byte[] memberImage;
	private Boolean isGroupBan;
	private Boolean isCommentBan;
	private Date notBanTime;
	private Date banTime;
	private Set<TabuUsernameTable> tabuUsernameTablesForToTabuMemberId = new HashSet<TabuUsernameTable>(
			0);
	private Set<TabuUsernameTable> tabuUsernameTablesForTabuMemberId = new HashSet<TabuUsernameTable>(
			0);
	private Set<StoreScore> storeScores = new HashSet<StoreScore>(0);
	private Set<GroupRoom> groupRooms = new HashSet<GroupRoom>(0);
	private Set<Member_FavoredType> memberFavoredTypes = new HashSet<Member_FavoredType>(
			0);

	public Member() {
	}

	public Member(int memberId, String username, byte[] pswd, String email,
			String lastname, String firstname, String idCard) {
		this.memberId = memberId;
		this.username = username;
		this.pswd = pswd;
		this.email = email;
		this.lastname = lastname;
		this.firstname = firstname;
		this.idCard = idCard;
	}

	public Member(int memberId, String username, byte[] pswd, String email,
			String lastname, String firstname, String gender,
			Serializable nickname, Date birthday, String idCard, Date joinDate,
			String phone, String memberAddress, String imgFileName,
			byte[] memberImage, Boolean isGroupBan, Boolean isCommentBan,
			Date notBanTime, Date banTime,
			Set<TabuUsernameTable> tabuUsernameTablesForToTabuMemberId,
			Set<TabuUsernameTable> tabuUsernameTablesForTabuMemberId,
			Set<StoreScore> storeScores, Set<GroupRoom> groupRooms,
			Set<Member_FavoredType> memberFavoredTypes) {
		this.memberId = memberId;
		this.username = username;
		this.pswd = pswd;
		this.email = email;
		this.lastname = lastname;
		this.firstname = firstname;
		this.gender = gender;
		this.nickname = nickname;
		this.birthday = birthday;
		this.idCard = idCard;
		this.joinDate = joinDate;
		this.phone = phone;
		this.memberAddress = memberAddress;
		this.imgFileName = imgFileName;
		this.memberImage = memberImage;
		this.isGroupBan = isGroupBan;
		this.isCommentBan = isCommentBan;
		this.notBanTime = notBanTime;
		this.banTime = banTime;
		this.tabuUsernameTablesForToTabuMemberId = tabuUsernameTablesForToTabuMemberId;
		this.tabuUsernameTablesForTabuMemberId = tabuUsernameTablesForTabuMemberId;
		this.storeScores = storeScores;
		this.groupRooms = groupRooms;
		this.memberFavoredTypes = memberFavoredTypes;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public byte[] getPswd() {
		return this.pswd;
	}

	public void setPswd(byte[] pswd) {
		this.pswd = pswd;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Serializable getNickname() {
		return this.nickname;
	}

	public void setNickname(Serializable nickname) {
		this.nickname = nickname;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMemberAddress() {
		return this.memberAddress;
	}

	public void setMemberAddress(String memberAddress) {
		this.memberAddress = memberAddress;
	}

	public String getImgFileName() {
		return this.imgFileName;
	}

	public void setImgFileName(String imgFileName) {
		this.imgFileName = imgFileName;
	}

	public byte[] getMemberImage() {
		return this.memberImage;
	}

	public void setMemberImage(byte[] memberImage) {
		this.memberImage = memberImage;
	}

	public Boolean getIsGroupBan() {
		return this.isGroupBan;
	}

	public void setIsGroupBan(Boolean isGroupBan) {
		this.isGroupBan = isGroupBan;
	}

	public Boolean getIsCommentBan() {
		return this.isCommentBan;
	}

	public void setIsCommentBan(Boolean isCommentBan) {
		this.isCommentBan = isCommentBan;
	}

	public Date getNotBanTime() {
		return this.notBanTime;
	}

	public void setNotBanTime(Date notBanTime) {
		this.notBanTime = notBanTime;
	}

	public Date getBanTime() {
		return this.banTime;
	}

	public void setBanTime(Date banTime) {
		this.banTime = banTime;
	}

	public Set<TabuUsernameTable> getTabuUsernameTablesForToTabuMemberId() {
		return this.tabuUsernameTablesForToTabuMemberId;
	}

	public void setTabuUsernameTablesForToTabuMemberId(
			Set<TabuUsernameTable> tabuUsernameTablesForToTabuMemberId) {
		this.tabuUsernameTablesForToTabuMemberId = tabuUsernameTablesForToTabuMemberId;
	}

	public Set<TabuUsernameTable> getTabuUsernameTablesForTabuMemberId() {
		return this.tabuUsernameTablesForTabuMemberId;
	}

	public void setTabuUsernameTablesForTabuMemberId(
			Set<TabuUsernameTable> tabuUsernameTablesForTabuMemberId) {
		this.tabuUsernameTablesForTabuMemberId = tabuUsernameTablesForTabuMemberId;
	}

	public Set<StoreScore> getStoreScores() {
		return this.storeScores;
	}

	public void setStoreScores(Set<StoreScore> storeScores) {
		this.storeScores = storeScores;
	}

	public Set<GroupRoom> getGroupRooms() {
		return this.groupRooms;
	}

	public void setGroupRooms(Set<GroupRoom> groupRooms) {
		this.groupRooms = groupRooms;
	}

	public Set<Member_FavoredType> getMemberFavoredTypes() {
		return this.memberFavoredTypes;
	}

	public void setMemberFavoredTypes(Set<Member_FavoredType> memberFavoredTypes) {
		this.memberFavoredTypes = memberFavoredTypes;
	}

}
