package model;

// Generated 2015/1/6 �W�� 11:59:56 by Hibernate Tools 3.4.0.CR1

/**
 * MemberFavoredType generated by hbm2java
 */
public class Member_FavoredType implements java.io.Serializable {

	private int memberFavoredId;
	private Member member;
	private String favoredType;

	public Member_FavoredType() {
	}

	public Member_FavoredType(int memberFavoredId, Member member) {
		this.memberFavoredId = memberFavoredId;
		this.member = member;
	}

	public Member_FavoredType(int memberFavoredId, Member member,
			String favoredType) {
		this.memberFavoredId = memberFavoredId;
		this.member = member;
		this.favoredType = favoredType;
	}

	public int getMemberFavoredId() {
		return this.memberFavoredId;
	}

	public void setMemberFavoredId(int memberFavoredId) {
		this.memberFavoredId = memberFavoredId;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getFavoredType() {
		return this.favoredType;
	}

	public void setFavoredType(String favoredType) {
		this.favoredType = favoredType;
	}

}
