package model;

// Generated 2015/1/6 �U�� 01:09:36 by Hibernate Tools 3.4.0.CR1

/**
 * StoreScore generated by hbm2java
 */
public class StoreScore implements java.io.Serializable {

	private int storeScoreId;
	private StoreInformation storeInformation;
	private Member member;
	private Double storeScore;
	private String storeScoreReason;

	public StoreScore() {
	}

	public StoreScore(int storeScoreId, StoreInformation storeInformation,
			Member member) {
		this.storeScoreId = storeScoreId;
		this.storeInformation = storeInformation;
		this.member = member;
	}

	public StoreScore(int storeScoreId, StoreInformation storeInformation,
			Member member, Double storeScore, String storeScoreReason) {
		this.storeScoreId = storeScoreId;
		this.storeInformation = storeInformation;
		this.member = member;
		this.storeScore = storeScore;
		this.storeScoreReason = storeScoreReason;
	}

	public int getStoreScoreId() {
		return this.storeScoreId;
	}

	public void setStoreScoreId(int storeScoreId) {
		this.storeScoreId = storeScoreId;
	}

	public StoreInformation getStoreInformation() {
		return this.storeInformation;
	}

	public void setStoreInformation(StoreInformation storeInformation) {
		this.storeInformation = storeInformation;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Double getStoreScore() {
		return this.storeScore;
	}

	public void setStoreScore(Double storeScore) {
		this.storeScore = storeScore;
	}

	public String getStoreScoreReason() {
		return this.storeScoreReason;
	}

	public void setStoreScoreReason(String storeScoreReason) {
		this.storeScoreReason = storeScoreReason;
	}

}
